sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky
    username: root
    password: 123456
  alioss:
    endpoint: 
    access-key-id: 
    access-key-secret: 
    bucket-name: 
